name: Import Notion to Github
on: 
  workflow_dispatch:
jobs:
  auto-sync-from-notion-to-github:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14.7.0'
          cache: 'npm'

      - run: npm install

      - name: Import Notion Docs
        run: NOTION_TOKEN=${{ secrets.NOTION_SECRET }} npm run import-notion-docs

      - name: Update folder permissions
        run: sudo chown -R $USER:$USER .

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.SECRET_GITHUB }}
          commit-message: Notion - Update docs
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: notion-update-docs
          delete-branch: false
          title: '[Notion] Update docs'
